import express from 'express';
import pkg from 'body-parser';
import dotenv from 'dotenv';
import cors from 'cors'
import bodyParser from "body-parser";
import path from "path";
import dbConfig from "./db.config/index.js"
import { fileURLToPath } from "url";
import setCorsHeaders from './Middleware/corsMiddleware.js';
import userRoute from './routes/user.routes.js';
import appCategory from './routes/appCategory.routes.js';
import videoCategoryRoute from './routes/videoCategory.routes.js';
import picCategoryRoute from './routes/picCategory.routes.js';
import itemCategoryRoute from './routes/itemCategory.routes.js';
import discCategoryRoute from './routes/discCategory.routes.js';
import blogRoute from './routes/blogs.routes.js';
import xpiRoute from './routes/xpiVideo.routes.js';
import picTourRoute from './routes/picToursCategory.routes.js';
import qafiRoute from './routes/qafiController.routes.js';
import gebcRoute from './routes/GEBC.routes.js';
import newsRoute from './routes/news.routes.js';
import topRoute from './routes/top.routes.js'
import signatureRoute from './routes/signature.routes.js';
import postLetterRoute from './routes/postLetter.routes.js';
import itemRoute from './routes/item.routes.js';
import bannerConfigRoute from './routes/bannerConfiguration.routes.js';
import bannerRoute from './routes/banner.routes.js';
import rateAppRoute from './routes/rateApp.routes.js';
import shareAppRoute from './routes/shareApp.routes.js';
import contactUsRoute from './routes/contactus.routes.js';
import massAppRoute from './routes/massApp.routes.js';
import paymentRoute from './routes/payment.routes.js';
import notificationType from './routes/notificationType.routes.js';
import notification from './routes/notification.routes.js';
import regionRoute from './routes/region.routes.js';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const app = express();
const port = 5022;
const { json } = pkg;
dotenv.config();
app.use(express.json());
app.use(setCorsHeaders);
app.use(bodyParser.urlencoded({ extended: true, limit: '50mb'}));
app.use(bodyParser.json({ limit: '50mb' }));
app.use(express.static(path.join(__dirname, "uploads")));
app.use(json());
app.use('/user', userRoute);
app.use('/app', appCategory);
app.use('/videoCategory', videoCategoryRoute);
app.use('/picCategory', picCategoryRoute);
app.use('/itemCategory', itemCategoryRoute);
app.use('/discCategory', discCategoryRoute);
app.use('/blog', blogRoute);
app.use('/xpi', xpiRoute);
app.use('/picTour', picTourRoute);
app.use('/qafi', qafiRoute);
app.use('/gebc', gebcRoute);
app.use('/news', newsRoute);
app.use('/top', topRoute);
app.use('/signature', signatureRoute);
app.use('/letter', postLetterRoute);
app.use('/item', itemRoute);
app.use('/bannerConfig', bannerConfigRoute);
app.use('/banner', bannerRoute);
app.use('/rateApp', rateAppRoute);
app.use('/shareApp', shareAppRoute);
app.use('/contact', contactUsRoute);
app.use('/massApp', massAppRoute);
app.use('/payment', paymentRoute);
app.use('/notification_type', notificationType);
app.use('/notification', notification);
app.use('/region', regionRoute);
const corsOptions = {
  origin: 'http://127.0.0.1:5173'
};
app.use(cors());
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
